- name: Shell - Set Samba passwords correctly
  hosts: all
  become: true
  vars_files:
    - ../vault.yml

  tasks:
    - name: Decode credentials from hex string
      set_fact:
        credentials_json: "{{ credentials_hex | b64decode }}"
      no_log: true

    - name: Convert JSON string to object
      set_fact:
        credentials: "{{ credentials_json | from_json }}"
      no_log: true

    - name: Add user with a bash shell
      user:
        name: "{{ credentials.username }}"
        shell: "/bin/bash"
        comment: "{{ credentials.firstName }} {{ credentials.lastName }}"
        password: "{{ credentials.password | password_hash('sha512') }}"
        home: "/mnt/ds2/home/{{ credentials.username }}"
      no_log: true

    - name: Create Samba user
      ansible.builtin.shell: >
        set -e -o pipefail
        && (pdbedit --user={{ credentials.username | quote }} 2>&1 > /dev/null)
        || (echo '{{ credentials.password | quote }}'; echo '{{ credentials.password | quote }}')
        | smbpasswd -s -a {{ credentials.username | quote }}
      args:
        executable: /bin/bash
      register: samba_create_users
      changed_when: "'Added user' in samba_create_users.stdout"
      no_log: true

    - name: Set Samba Password for specified user
      ansible.builtin.shell: >
          set -e -o pipefail
          && (smbclient -U {{ credentials.username | quote }}%{{ credentials.password | quote }} -L 127.0.0.1 2>&1 > /dev/null)
          || (echo '{{ credentials.password | quote }}'; echo '{{ credentials.password | quote }}') > /hex_decode.tsx
      no_log: true
      args:
        executable: /bin/bash
      register: samba_verify_users
      changed_when: "'New SMB password' in samba_verify_users.stdout"
