---
- name: Shell - Set Samba passwords correctly
  hosts: all
  become: true
  vars_files:
    - ../vault.yml

  tasks:
    - name: Decode credentials from base64
      set_fact:
        decoded_credentials: "{{ credentials | b64decode | from_json }}"
      no_log: true

    - name: Add user with a bash shell
      user:
        name: "{{ decoded_credentials.username }}"
        shell: "/bin/bash"
        comment: "{{ decoded_credentials.firstName }} {{ decoded_credentials.lastName }}"
        password: "{{ decoded_credentials.password | password_hash('sha512') }}"
        home: "/mnt/ds2/home/{{ decoded_credentials.username }}"
      no_log: true

    - name: Create Samba user
      ansible.builtin.shell: >
        set -e -o pipefail
        && (pdbedit --user='{{ decoded_credentials.username | quote }}' 2>&1 > /dev/null)
        || (echo '{{ decoded_credentials.password | quote }}'; echo '{{ decoded_credentials.password | quote }}')
        | smbpasswd -s -a {{ decoded_credentials.username | quote }}
      args:
        executable: /bin/bash
      register: samba_create_users
      changed_when: "'Added user' in samba_create_users.stdout"
      no_log: true

    - name: Set Samba Password for specified user
      ansible.builtin.shell: >
        set -e -o pipefail
        && (smbclient -U '{{ decoded_credentials.username | quote }}%{{ decoded_credentials.password | quote }}' -L 127.0.0.1 2>&1 > /dev/null)
        || (echo '{{ decoded_credentials.password | quote }}'; echo '{{ decoded_credentials.password | quote }}') > /notworking.txt
      no_log: true
      args:
        executable: /bin/bash
      register: samba_verify_users
      changed_when: "'New SMB password' in samba_verify_users.stdout"
