---
- name: Shell - Set Samba passwords correctly
  hosts: all
  become: true
  #gather_facts: no
  vars_files:
    - ../vault.yml

  tasks:
    - name: Add user with a bash shell
      user:
        name: "{{ username }}"
        shell: "/bin/bash"
        #groups: wheel
        #append: yes
        comment: "{{ firstname }} {{ lastname }}"
        password: "{{ password | password_hash('sha512') }}"
        home: "/mnt/ds2/home/{{ username }}"
        #generate_ssh_key: true
        #ssh_key_type: ssh-ed25519

    - name: Create Samba user
      ansible.builtin.shell: >
        set -e -o pipefail
        && (pdbedit --user={{ username | quote }} 2>&1 > /dev/null)
        || (echo '{{ password | quote }}'; echo '{{ password | quote }}')
        | smbpasswd -s -a {{ username | quote }}
      args:
        executable: /bin/bash
      register: samba_create_users
      changed_when: "'Added user' in samba_create_users.stdout"
      no_log: true

    - name: Set Samba Password for specified user
      ansible.builtin.shell: >
          set -e -o pipefail
          && (smbclient -U {{ username | quote }}%{{ password | quote }} -L 127.0.0.1 2>&1 > /dev/null)
          || (echo '{{ password | quote }}'; echo '{{ password | quote }}')
          | smbpasswd {{ username | quote }}
      no_log: true
      args:
        executable: /bin/bash
      register: samba_verify_users
      changed_when: "'New SMB password' in samba_verify_users.stdout"
