---
- name: Shell - Set Samba passwords correctly
  hosts: all
  become: true
  #gather_facts: no
  vars_files:
    - ../vault.yml

  tasks:
    - name: Set Samba Password for specified user
      ansible.builtin.shell: >
        set -e -o pipefail
        && (smbclient -U {{ username }}%{{ password }} -L 127.0.0.1 2>&1 > /dev/null)
        || (echo '{{ password }}'; echo '{{ password }}')
        | smbpasswd {{ username }}
      args:
        executable: /bin/bash
      register: samba_verify_users
      changed_when: "'New SMB password' in samba_verify_users.stdout"
      no_log: true
